export default {
  Login: 'login',
  SignUp: 'signup',
  Home: 'home',
  Player: 'player',
  Schedules: 'schedules',
  Contact: 'contact',
  TopStats: 'top-stats',
  Players: 'players',
  Leagues: 'leagues',
  Rules: 'rules',
  CreateLeague: 'create-league',
  League: 'league',
  StartLeague: 'start-league',
  GameSummary: 'game-summary',
  SubmitScore: 'submit-score',
  Games: 'games',
  NotFound: 'not-found',
}