const leagues = [
  {
    "name": "Summer 2021 Mens League",
    "player_ids": [1, 2, 3, 4, 5, 6],
    "player_stats": [],
    "max_num_players": 6,
    "league_creator_id": 1,
    "game_ids": [1, 2, 3, 4],
    "num_games": 4,
    "games_created": false,
    "team_size": 3,
    "start_date": new Date(Date.now()),
    "end_date": new Date(Date.now()),
    "deadline_date": new Date(Date.now()),
    "about_text": "about text"
  },
  {
    "name": "Summer 2021 Womens League",
    "player_ids": [1, 2, 3, 4, 5, 6],
    "player_stats": [],
    "max_num_players": 6,
    "league_creator_id": 1,
    "game_ids": [1, 2, 3, 4],
    "num_games": 4,
    "games_created": false,
    "team_size": 3,
    "start_date": new Date(Date.now()),
    "end_date": new Date(Date.now()),
    "deadline_date": new Date(Date.now()),
    "about_text": "about text"
  },
  {
    "name": "Fall 2021 Mens League",
    "player_ids": [1, 2, 3, 4, 5, 6],
    "player_stats": [],
    "max_num_players": 6,
    "league_creator_id": 1,
    "game_ids": [1, 2, 3, 4],
    "num_games": 4,
    "games_created": false,
    "team_size": 3,
    "start_date": new Date(Date.now()),
    "end_date": new Date(Date.now()),
    "deadline_date": new Date(Date.now()),
    "about_text": "about text"
  },
  {
    "name": "Fall 2021 Womens League",
    "player_ids": [1, 2, 3, 4, 5, 6],
    "player_stats": [],
    "max_num_players": 6,
    "league_creator_id": 1,
    "game_ids": [1, 2, 3, 4],
    "num_games": 4,
    "games_created": false,
    "team_size": 3,
    "start_date": new Date(Date.now()),
    "end_date": new Date(Date.now()),
    "deadline_date": new Date(Date.now()),
    "about_text": "about text"
  },
  {
    "name": "Cool League",
    "player_ids": [1, 2, 3, 4, 5, 6],
    "player_stats": [],
    "max_num_players": 6,
    "league_creator_id": 1,
    "game_ids": [1, 2, 3, 4],
    "num_games": 4,
    "games_created": false,
    "team_size": 3,
    "start_date": null,
    "end_date": null,
    "deadline_date": null,
    "about_text": "about text"
  },
  {
    "name": "Ez League",
    "player_ids": [1, 2, 3, 4, 5, 6],
    "player_stats": [],
    "max_num_players": 6,
    "league_creator_id": 1,
    "game_ids": [1, 2, 3, 4],
    "num_games": 4,
    "games_created": false,
    "team_size": 3,
    "start_date": null,
    "end_date": null,
    "deadline_date": null,
    "about_text": "about text"
  },
  {
    "name": "Fun League",
    "player_ids": [1, 2, 3, 4, 5, 6],
    "player_stats": [],
    "max_num_players": 6,
    "league_creator_id": 1,
    "game_ids": [1, 2, 3, 4],
    "num_games": 4,
    "games_created": false,
    "team_size": 3,
    "start_date": null,
    "end_date": null,
    "deadline_date": null,
    "about_text": "about text"
  },
  {
    "name": "Dumb League",
    "player_ids": [1, 2, 3, 4, 5, 6],
    "player_stats": [],
    "max_num_players": 6,
    "league_creator_id": 1,
    "game_ids": [1, 2, 3, 4],
    "num_games": 4,
    "games_created": false,
    "team_size": 3,
    "start_date": null,
    "end_date": null,
    "deadline_date": null,
    "about_text": "about text"
  },
  {
    "name": "Free League",
    "player_ids": [1, 2, 3, 4, 5, 6],
    "player_stats": [],
    "max_num_players": 6,
    "league_creator_id": 1,
    "game_ids": [1, 2, 3, 4],
    "num_games": 4,
    "games_created": false,
    "team_size": 3,
    "start_date": null,
    "end_date": null,
    "deadline_date": null,
    "about_text": "about text"
  },
  {
    "name": "Dog water League",
    "player_ids": [1, 2, 3, 4, 5, 6],
    "player_stats": [],
    "max_num_players": 6,
    "league_creator_id": 1,
    "game_ids": [1, 2, 3, 4],
    "num_games": 4,
    "games_created": false,
    "team_size": 3,
    "start_date": null,
    "end_date": null,
    "deadline_date": null,
    "about_text": "about text"
  },
  {
    "name": "Ur mom League",
    "player_ids": [1, 2, 3, 4, 5, 6],
    "player_stats": [],
    "max_num_players": 6,
    "league_creator_id": 1,
    "game_ids": [1, 2, 3, 4],
    "num_games": 4,
    "games_created": false,
    "team_size": 3,
    "start_date": null,
    "end_date": null,
    "deadline_date": null,
    "about_text": "about text"
  },
]

module.export = leagues